title: Luma Gaudard
logo: logo: /assets/img/4png
description: Olá, este é o meu portfólio de projetos. Aqui, eu compartilho como aplico Análise de Dados, Estatística e Machine Learning na resolução de problemas de negócios.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

[Link to another page](./another-page.html).
